//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por pagina en blanco.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     103
#define IDD_DIALOG3                     105
#define IDD_DIALOG4                     107
#define IDR_MENU1                       109
#define BTN_ModificarListCliente        109
#define IDR_MENU2                       110
#define IDD_DIALOG5                     111
#define IDD_DIALOG6                     113
#define IDD_DIALOG7                     115
#define IDD_DIALOG8                     117
#define IDD_DIALOG9                     119
#define IDD_DIALOG10                    121
#define IDD_DIALOG11                    123
#define IDD_DIALOG12                    127
#define IDD_DIALOG13                    129
#define IDD_DIALOG14                    131
#define EDIT_InicioUs                   1001
#define EDIT_InicioCont                 1002
#define EDIT_InicioComercio             1003
#define IDC_EDIT4                       1004
#define IDC_BUTTON1                     1005
#define BTN_Registrar                   1006
#define BTN_RegresarInicio              1007
#define EDIT_RUsuario                   1008
#define EDIT_RContrasenia               1009
#define EDIT_RComercio                  1010
#define CB_TipoDeUs                     1011
#define BTN_Entrar                      1012
#define BTN_InicioSalir                 1013
#define EDIT_InfoUs                     1014
#define EDIT_InfoNCUs                   1015
#define IDC_DireccionInfo               1016
#define BTN_RegresarInfoInicio          1017
#define BTN_ModificarInfoUs             1018
#define IDC_COMBO1                      1019
#define EDIT_InfoCom                    1020
#define BTN_OKInfoUS                    1021
#define FotoUsuario                     1022
#define LISTA_Usuarios                  1023
#define EDIT_NombreListUs               1024
#define EDIT_NomComListUs               1025
#define EDIT_ComercioList               1026
#define BTN_EliminarListUs              1027
#define BTN_RegresarListUsInicio        1028
#define BTN_RegistrarListUs             1029
#define BTN_CambiarFotoListUs           1030
#define BTN_ModificarListUs             1031
#define EDIT_DireccionListaUs           1032
#define IDC_COMBO2                      1033
#define STATIC_NombreTipoUs             1034
#define Foto1                           1035
#define Foto2                           1036
#define EDIT_NombreAltaUS               1037
#define EDIT_AltaContrasenia            1038
#define Static_NombreAltaUS             1039
#define BTN_AceptarAltaUS               1040
#define BTN_SalirAltaUS                 1041
#define IDC_COMBO3                      1042
#define IDC_COMBO4                      1043
#define FotoAltaUs                      1044
#define EDIT_ContraActual               1046
#define EDIT_ContraNueva                1047
#define STATIC_NombreCambiarContra      1048
#define Foto3                           1049
#define BTN_CambiarContra               1050
#define BTN_RegresarContraInicio        1051
#define LISTA_USCambiarContrasenia      1052
#define EDIT_NombreAltaCliente          1053
#define EDIT_AltaClienteEmail           1054
#define IDC_COMBO5                      1057
#define IDC_Calendario                  1058
#define Foto5                           1059
#define BTN_AltaClienteSalir            1060
#define BTN_AceptarAltaCliente          1061
#define STATIC_AltaCliente              1062
#define STATIC_NombreManejadorAltaCliente 1063
#define Foto6                           1064
#define EDIT_NombreListaclientes        1065
#define EDIT_EmailListaClientes         1066
#define IDC_COMBO6                      1067
#define IDC_CalendarioListaClientes     1068
#define BTN_RegresarListClientesInicio  1069
#define BTN_ModificarListClientes       1070
#define BTN_EliminarListCliente         1072
#define LISTA_Clientes                  1073
#define BOTON_ModificarListaClientes    1074
#define EDIT_ClienteAltaConsumo         1075
#define EDIT_MontoAltaConsumo           1076
#define EDIT_DescuentoAltaConsumos      1078
#define EDIT_TotalAltaConsumo           1079
#define ID_CalendarioAltaConsumos       1080
#define LISTA_AltaConsumos              1081
#define EDIT_IDAltaConsumo              1082
#define EDIT_ComercioAltaConsumo        1083
#define BTN_AceptarAltaConsumo          1084
#define BTN_SalirAltaConsumos           1085
#define BTN_CalcularAltaConsumos        1086
#define EDIT_SubtotalAltaConsumo        1087
#define STATIC_NombreManejadorAltaConsumo 1088
#define Foto7                           1089
#define EDIT_ClienteListaConsumos       1090
#define EDIT_MontoListaConsumos         1091
#define EDIT_SubtotalListaConsumos      1092
#define EDIT_DescListaConsumos          1093
#define EDIT_TotalListaConsumos         1094
#define EDIT_FechaListaConsumos         1095
#define BTN_RegresarListaConsumosInicio 1096
#define LISTA_ListConsumos              1097
#define Foto8                           1098
#define STATIC_NombreManejadorListaConsumos 1099
#define EDIT_FiltroConsumosCliente      1112
#define EDIT_FiltroConsumosMonto        1113
#define EDIT_FiltroConsumoDesc          1114
#define EDIT_FiltrosConsumoSubtotal     1115
#define EDIT_FiltroConsumoTotal         1116
#define EDIT_FiltroConsumoFecha         1117
#define FOTO10                          1118
#define STATIC_NombreManejadorFiltroConsumo 1119
#define BTN_FiltroConsumoSalir          1120
#define IDC_LIST1                       1121
#define IDC_LIST2                       1122
#define EDIT_NombreAltaPromo            1123
#define EDIT_ComercioAltaPromo          1124
#define EDIT_MontoAltaPromo             1125
#define EDIT_DescuentoAltaPromo         1126
#define Calendario_AltaPromo            1128
#define RADIO_Activo                    1129
#define IDC_RADIO2                      1130
#define FOTO11                          1131
#define STATIC_NombreManejadorAltaPromo 1132
#define BTN_ModificarAltaPromo          1133
#define BTN_RegistrarAltaPromo          1134
#define BTN_EliminarAltaPromo           1135
#define BTN_RegresarAltaPromo           1137
#define ID_RegistrarListaPromocion      1138
#define EDIT_NombreListaPromo           1139
#define EDIT_MontoListaPromo            1140
#define EDIT_DescuentoListaPromo        1141
#define EDIT_FechaListaPromo            1142
#define BTN_RegresarListaPromo          1143
#define IDC_RADIO1                      1144
#define RADIO_ActivoListaPromo          1144
#define FOTO12                          1145
#define STATIC_NombreManejadorListAPromo 1146
#define LISTA_ListaPromo                1147
#define BTN_EliminarListaPromo          1148
#define BTN_ModificarListaPromo         1150
#define RADIO_InactivoListaPromo        1151
#define ID_USUARIOS_INFORMACI40001      40001
#define ID_USUARIOS_LISTA               40002
#define ID_USUARIOS_DARDEALTA           40003
#define ID_USUARIOS_RESTABLECERCONTRASE40004 40004
#define ID_CLIENTE_DARDEAL              40005
#define ID_CLIENTE_PROMOCIONES          40006
#define ID_CONSUMO_DARDEALTA            40007
#define ID_CONSUMO_LISTADECONSUMOS      40008
#define ID_CONSUMO_FILTRODECONSUMOS     40009
#define ID_PROMOCIONES_DARDEALTA        40010
#define ID_PROMOCIONES_LISTADEPROMOCIONES 40011
#define ID_SALIR                        40012
#define ID_SALIR_CERRARSESI40013        40013
#define ID_CLIENTES_PROMOCIONES         40014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
